### ISSUE TITLE
Difference to EXT:fal_securedownload

### ISSUE THREAD

**Issue by EvilBMP** [calien666/typo3-secure-filemount#6]
Hi,

I just found your extension by searching the TER and by looking at it quickly it seems like the extension does quite the same as EXT:fal_securedownload?! Is this the case or is there something different, that I missed? 

(As I said, I didn't compare the details nor the code itself)

Thanks :-)

**Comment by calien666** [comment]
Hi @EvilBMP,

In contrast to fal_securedownload, however, this extension can only secure folders individually and not down to file level.
The background was to create a core-like extension that does not involve too much configuration, is easy to use and still guarantees handling in the frontend via the normal core functionalities.

fal_securedownload also controls the shares per user group. However, in this case files are included via dumpFile and eID, which makes it difficult to pass on file links in a readable form. My extension solves the problem by outputting the file names as a speaking URL, but a middleware intervenes, which then checks the share accordingly for non-public access and either returns the file or an "authentication required" message.
As fal_securedownload ships a setting for 403 handling, my extension works with the default from the site configuration, so file access and page access are handled by the same errorHandling.
Also unlike fal_securedownload, this extension does not set up the FE user authorisation itself, but takes the data transmitted with the request as given. The folder path is broken down and verified against an access table containing the respective settings.

All accesses and functions that run within TYPO3 are also given by default in this extension, such as search indexing, as this normally triggers a backend request, which the extension has no influence on.

Which one you want to use is in your flavour. I had some things I didn't like on fal_securedownload, but this doesn't mean, this extension is bad. My intention was a small, lightweight and easy to use extension with the usage of the real filenames. That's why I built this extension.

And, if your'e waiting for v12 support, I'm on it, there are only small things to do and v12 will be supported.

**Comment by calien666** [comment]
Hi @EvilBMP,
I hope, I could answer your question. Unfortunately I got no feedback. I will close this issue for now.
